# Generated by Django 4.0.1 on 2023-02-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportfolio',
            name='description',
        ),
    ]
