# Generated by Django 4.0.1 on 2023-02-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_userportfolio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportfolio',
            name='name',
        ),
    ]
