# Generated by Django 4.0.1 on 2023-02-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_userportfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='coin_buy_date',
            field=models.DateField(),
        ),
    ]
